-- COPIA COMBINADA PARA PEGAR DE UNA SOLA VEZ EN EL SQL EDITOR DE SUPABASE.
-- Es la union, en orden, de 0002_inventario.sql + 0003_seed_inventario_maquinas.sql
-- + 0004_seed_inventario_towing.sql. Correr una sola vez; no volver a correr
-- este archivo (ni los tres originales) despues de haberlo corrido, porque
-- "create table" fallaria al encontrar las tablas ya creadas.
--
-- Modulo de inventario: maquinas y towing gear.
-- Las cantidades solo se modifican a traves de inventario_movimientos (alta/baja
-- con motivo y detalle); el resto de los campos del item se edita directamente.

create table atlantic_dama.ubicaciones (
  id uuid primary key default gen_random_uuid(),
  nombre text not null unique,
  descripcion text,
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create table atlantic_dama.motivos_movimiento (
  id uuid primary key default gen_random_uuid(),
  nombre text not null unique,
  tipo text not null check (tipo in ('alta', 'baja', 'ambos')),
  activo boolean not null default true,
  orden int not null default 0
);

create table atlantic_dama.inventario_items (
  id uuid primary key default gen_random_uuid(),
  categoria text not null,
  grupo text,
  nombre text not null,
  codigo text,
  marca text,
  cantidad numeric not null default 0 check (cantidad >= 0),
  ubicacion_id uuid references atlantic_dama.ubicaciones(id) on delete set null,
  wll_mbl text,
  fecha_referencia date,
  estado text not null default 'activo' check (estado in ('activo', 'cuarentena', 'baja')),
  comentarios text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table atlantic_dama.inventario_movimientos (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references atlantic_dama.inventario_items(id) on delete cascade,
  tipo text not null check (tipo in ('alta', 'baja')),
  cantidad numeric not null check (cantidad > 0),
  motivo_id uuid references atlantic_dama.motivos_movimiento(id),
  detalle text,
  usuario_email text,
  created_at timestamptz not null default now()
);

create index inventario_items_categoria_idx on atlantic_dama.inventario_items(categoria);
create index inventario_items_ubicacion_idx on atlantic_dama.inventario_items(ubicacion_id);
create index inventario_movimientos_item_idx on atlantic_dama.inventario_movimientos(item_id);

alter table atlantic_dama.ubicaciones enable row level security;
alter table atlantic_dama.motivos_movimiento enable row level security;
alter table atlantic_dama.inventario_items enable row level security;
alter table atlantic_dama.inventario_movimientos enable row level security;

create policy "authenticated_all_ubicaciones" on atlantic_dama.ubicaciones
  for all to authenticated using (true) with check (true);

create policy "authenticated_all_motivos_movimiento" on atlantic_dama.motivos_movimiento
  for all to authenticated using (true) with check (true);

create policy "authenticated_all_inventario_items" on atlantic_dama.inventario_items
  for all to authenticated using (true) with check (true);

-- Los movimientos son un registro de auditoria: se pueden crear y leer, pero no
-- editar ni borrar (evita reescribir el historial de altas/bajas).
create policy "authenticated_select_inventario_movimientos" on atlantic_dama.inventario_movimientos
  for select to authenticated using (true);

create policy "authenticated_insert_inventario_movimientos" on atlantic_dama.inventario_movimientos
  for insert to authenticated with check (true);

create or replace function atlantic_dama.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger inventario_items_set_updated_at
  before update on atlantic_dama.inventario_items
  for each row execute function atlantic_dama.set_updated_at();

-- Cada movimiento ajusta el stock del item automaticamente: alta suma,
-- baja resta (sin bajar de cero).
create or replace function atlantic_dama.aplicar_movimiento_inventario()
returns trigger as $$
begin
  if new.tipo = 'alta' then
    update atlantic_dama.inventario_items
      set cantidad = cantidad + new.cantidad
      where id = new.item_id;
  else
    update atlantic_dama.inventario_items
      set cantidad = greatest(cantidad - new.cantidad, 0)
      where id = new.item_id;
  end if;
  return new;
end;
$$ language plpgsql;

create trigger inventario_movimientos_aplicar
  after insert on atlantic_dama.inventario_movimientos
  for each row execute function atlantic_dama.aplicar_movimiento_inventario();

insert into atlantic_dama.motivos_movimiento (nombre, tipo, orden) values
  ('Compra', 'alta', 1),
  ('Devolucion', 'alta', 2),
  ('Instalacion', 'baja', 3),
  ('Utilizacion / Consumo', 'baja', 4),
  ('Rotura', 'baja', 5),
  ('Perdida', 'baja', 6),
  ('Ajuste de inventario', 'ambos', 7);
-- Datos migrados desde "INVENTARIO ATLANTIC DAMA Rev AGOSTO 2025.xlsb.xlsx"
-- (hojas HERRAMIENTAS MAQ, HERRAMIENTAS CUB y REPUESTOS).
insert into atlantic_dama.ubicaciones (nombre) values
  ('Caja de mechas'),
  ('Camarote JDM'),
  ('Cubierta - punto de reunión'),
  ('En Tigre (Ing. Emilio)'),
  ('En uso'),
  ('Frente a generador 2'),
  ('Frente separador de sentinas'),
  ('Pañol de cubierta'),
  ('Pañol de proa'),
  ('Pañol de timón'),
  ('Proa'),
  ('Sala de máquinas (SDM)'),
  ('Taller SCL Naval (astillero)'),
  ('Taller de máquinas'),
  ('Taquilla BB (SDM)');

insert into atlantic_dama.inventario_items
  (categoria, grupo, nombre, codigo, cantidad, ubicacion_id, comentarios)
select * from (values
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'ALICATE DE 6''''', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'APAREJO DE 2 TON', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'LUSQTOFF'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'ARCO DE CIERRA', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'BARRETA DE 1,5 M', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'BARRETA DE 2 M', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'BARRETA DE 500 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'BOMBA DE TRASVASE DE LUBRICANTES ELECT. C/MOTOR 3/4HP', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Cubierta - punto de reunión'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'BOMBA NEUMATICA INDESUR Nº4', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Sala de máquinas (SDM)'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'BOMBA SUMERGIBLE', null, 2, (select id from atlantic_dama.ubicaciones where nombre = ''), 'Ubicacion original (a revisar): 1 en SDM, 1 en Camarote JDM'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'BUSCAPOLO', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'destornillador'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'CALIBRE 270 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'CARGADOR DE BATERIA 24V', null, 2, (select id from atlantic_dama.ubicaciones where nombre = ''), 'Ubicacion original (a revisar): 1 en uso, 1 en Pañol de proa'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'FAJAS Y ESLINGAS VARIAS', null, 4, (select id from atlantic_dama.ubicaciones where nombre = ''), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LAPIZ BUSCADOR DE TENSION', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 1/2', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 10', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 11', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 12', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 13', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 14', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 15', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 16', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 17', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 18', null, 0, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 19', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 20', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 21', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 22', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 23', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 24', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 25', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 26', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 27', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 28', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 29', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 3/4', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 30', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 31', null, 0, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 32', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 33', null, 0, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 34', null, 0, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 35', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 36', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 37', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 38', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 39', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 41', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 5/16', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 5/8', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 50', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 6', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 7', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 7/16', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 7/8', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 8', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 9', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 9/16', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE FRANCESA 8" MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE STILSON 14"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE STILSON 24"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE STILSON BAHCO 65 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE TORX T10', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE TORX T15', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE TORX T20', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE TORX T25', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE TORX T27', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE TORX T30', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE TORX T40', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE TORX T45', null, 0, (select id from atlantic_dama.ubicaciones where nombre = ''), 'EN USO. Ubicacion original (a revisar): esta usada en TIMON modo manual'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE TORX T50', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'MARTILLO BOLITA', null, 3, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'MASCARA DE SOLDAR', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'MULTIMETRO', null, 1, (select id from atlantic_dama.ubicaciones where nombre = ''), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'MULTITESTER', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'PICO DE LORO', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'PINZA DE PUNTA', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'PINZA PARA SEGUER EXTERNO 40-100', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'PINZA PARA SEGUER INTERNO 40-100', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'PINZA UNIVERSAL 8"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = ''), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'PISTOLA DE CALOR EIHEM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'PISTOLA PARA POMO FASTIX', null, 2, (select id from atlantic_dama.ubicaciones where nombre = ''), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'PISTOLA PARA TOMAR TEMPERATURA', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Sala de máquinas (SDM)'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'PROTECTOR FACIAL', null, 2, (select id from atlantic_dama.ubicaciones where nombre = ''), 'Ubicacion original (a revisar): 1 Camarote JDM, 1 en uso'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'REGLA DE ACERO INOXIDABLE 1 MT', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'En Tigre (Ing. Emilio)'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'REMACHADORA POP', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Sala de máquinas (SDM)'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'ROTOMARTILLO DE 13MM', 'TCRH620', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'SET SACABOCADOS', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TENAZA', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TIJERA DE HOJALATA', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'Estado regular'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TIJERA DE SASTRE', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'VENTILADOR Y MANGA', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'MACHO 3/8" X 16', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Caja de mechas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'MACHO 5/16" X 24', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Caja de mechas'), 'Rosca UNF'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'MECHA DE ACERO RAPIDO 13 MM', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'MECHA DE ACERO RAPIDO 4MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'MECHA DE ACERO RAPIDO 6,5 MM', null, 5, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'MECHA DE ACERO RAPIDO 8 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'Reafilada'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'MECHA DE ACERO RAPIDO 8,5 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'MECHA DE ACERO RAPIDO17 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'ACEITERA', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'ADAPTADOR PARA TUBOS DE 1/2" A 3/4"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'En caja de desarme de vulkan'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'CINTA METRICA DE 3M', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'DESTORNILLADOR PHILIPS 90 MM', null, 5, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'Todos en muy mal estado'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'DESTORNILLADOR PLANO DE 100 MM', null, 8, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'DESTORNILLADOR PLANO DE 140 MM', null, 3, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'DESTORNILLADOR PLANO DE 190 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'ESCUADRA DE 300 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'EXTENSOR BAHCO 786', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'En caja de desarme de vulkan'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'EXTRACTOR DE FILTROS', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'JUEGO DE TUBOS CON MANIJA CRIQUET, EXTENSOR MANIJA DE FUERZA Y CARDAN', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LIMA REDONDA 190 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE FRANCESA 300 MM', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'MANIJA DE FUERZA BAHCO 706A', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'En caja de desarme de vulkan'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'MARTILLO GALPONERO', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'MASA DE 5 KG', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'PINZA DE PRESION DIENTE DE PERRO', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'PISTOLA NEUMATICA C/ACOPLE DE 1/2', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'En caja de desarme de vulkan'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'PUNTA CRIQUET', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'En caja de desarme de vulkan'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'RASQUETA DE 120 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'RASQUETA DE 70 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TALADRO DE MANO DE 10 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO ALLEN 19 MM CON ENCASTRE 1/2"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'En caja de desarme de vulkan'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 10', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 11', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 12', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 13', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 14', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 15', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 16', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 17', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 18', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 19', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 20', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 21', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 22', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 23', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 24', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 25', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 26', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 27', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 28', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 3/8"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 30', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'Uno en caja de desarme de vulkan con encastre 3/4"'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 32', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'Uno en caja de desarme de vulkan'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 36 CON ENCASTRE 3/4"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'En caja de desarme de vulkan'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 46 CON ENCASTRE 3/4"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'En caja de desarme de vulkan'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº 5/16"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'DESTORNILLADOR PHILIPS 152 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = ''), 'Nuevo, con punta imantada'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'DESTORNILLADOR PHILIPS 1PT 100 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = ''), 'Nuevo'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'DESTORNILLADOR PHILIPS 200 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = ''), 'Nuevo, con punta imantada'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'DESTORNILLADOR PHILIPS 2PT 100 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = ''), 'Nuevo'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'DESTORNILLADOR PHILIPS 65 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = ''), 'Nuevo, con punta imantada'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'DESTORNILLADOR PLANO 5M 150 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = ''), 'Nuevo'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'DESTORNILLADOR PLANO 5M 75 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = ''), 'Nuevo'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'DESTORNILLADOR PLANO 6M 100 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = ''), 'Nuevo'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'DESTORNILLADOR PLANO 6M 150 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = ''), 'Nuevo'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LIMA MEDIA CAÑA 10"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'NUEVA'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LIMA PLANA 10"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'NUEVA'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 1,5 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'NUEVA'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 1/16"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'NUEVA'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 1/4"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'NUEVA'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 1/8"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'NUEVA'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 10 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'NUEVA'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 2 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'NUEVA'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 2,5 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'NUEVA'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 3 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'NUEVA'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 3/16"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'NUEVA'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 3/32"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'NUEVA'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 3/8"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'NUEVA'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 4 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'NUEVA'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 5 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'NUEVA'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 5/16"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'NUEVA'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 5/32"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'NUEVA'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 5/64"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'NUEVA'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 6 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'NUEVA'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 7/32"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'NUEVA'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 7/64"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'NUEVA'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 8 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'NUEVA'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 9/64"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), 'NUEVA'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'PINZA AMPEROMETRICA', 'EM87', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), 'caja de herramientas stanley'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'ANTEOJOS DE SEGURIDAD', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'BBA SUMERGIBLE 1000W 20 MT ELEVACION', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'ARRANCADOR ,CARGADOR DE BATERIAS', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'CUTTER', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), 'caja de herramientas stanley'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE DE GOLPE 46 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'En caja de desarme de vulkan'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'PUENTE MANOMETRICO', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'SB12:F209ONDA CON PILON BRONCE X LLENO', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE DE GOLPE 32 MM', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'En caja de desarme de vulkan'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 22 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'En caja de desarme de vulkan'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 20 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'En caja de desarme de vulkan'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 19 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'En caja de desarme de vulkan'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 18 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'En caja de desarme de vulkan'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE ALLEN 17 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'En caja de desarme de vulkan'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'SET DE POWER HIDRAULICO', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'MASA DE 3 KG', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LIMA REDONDA 240 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'JUEGO DE MECHAS VARIAS MEDIDAS (10 unidades)', null, 1, (select id from atlantic_dama.ubicaciones where nombre = ''), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'CINTO ARNES PARA TRABAJO EN ALTURA', null, 1, (select id from atlantic_dama.ubicaciones where nombre = ''), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'APAREJO DE 1 TON GAN-MAR', null, 1, (select id from atlantic_dama.ubicaciones where nombre = ''), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'AMOLADORA CHICA DE 4''''', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'De-Walt'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'AMOLADORA GRANDE DE 7''''', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), '1 De-Walt, 1 Makita'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'AGUJEREADORA CHICA DE 12MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Sala de máquinas (SDM)'), 'De-Walt'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'EEBD (EQUIPO DE ESCAPE RAPIDO)', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LAPIZ BUSCADOR DE TENSION', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE FRANCESA 12"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller SCL Naval (astillero)'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE FRANCESA 10"', null, 2, (select id from atlantic_dama.ubicaciones where nombre = ''), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'MAZA 500g CON MANGO', null, 3, (select id from atlantic_dama.ubicaciones where nombre = ''), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE BISEGRIP', null, 1, (select id from atlantic_dama.ubicaciones where nombre = ''), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE CADENA SACA FILTROS', null, 2, (select id from atlantic_dama.ubicaciones where nombre = ''), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LUCES PORTATILES', null, 2, (select id from atlantic_dama.ubicaciones where nombre = ''), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'EMBUDOS PLASTICOS VARIAS MEDIDAS', null, 6, (select id from atlantic_dama.ubicaciones where nombre = ''), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'SONDA SONDAJE POR LLENO 10m DIAMANTE', null, 2, (select id from atlantic_dama.ubicaciones where nombre = ''), 'Ubicacion original (a revisar): 1 en uso, 1 en Camarote JDM'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LINTERNA LED MINERO', null, 2, (select id from atlantic_dama.ubicaciones where nombre = ''), 'Ubicacion original (a revisar): 1 en Camarote de JDM'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'DISPENSER AGUA FRIA CALIENTE', null, 1, (select id from atlantic_dama.ubicaciones where nombre = ''), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'BBA RELOJ PARA TRASVASES HIDRAULICOS AZUL', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'mal estado'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'PIEDRA DE AMOLAR Y CEPILLO ELECTRICA DE BANCO', null, 1, (select id from atlantic_dama.ubicaciones where nombre = ''), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'BOMBA RELOJ PARA TRASVASES DE LUBRICANTES', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'En uso'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'JUEGO DE LETRAS PARA ESTAMPAR', null, 1, (select id from atlantic_dama.ubicaciones where nombre = ''), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'CONJUNTO CORTADORA CAÑOS DE COBRE Y PESTAÑADORA', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 6', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 8', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 10', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 11', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 12', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 13', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 14', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 17', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 18', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 19', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 22', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 24', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 25', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE COMBINADA Nº 27', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'MASA DE 3 KG', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'MASA DE 2 KG', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'MASA DE 1 KG', null, 3, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'ZERRUCHO  DE 26"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'ARCO DE SIERRA', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'MARTILLO GALPONERO', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'PINZA UNIVERSAL', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'ALICANTE', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TENAZA CHICA', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'LLAVE FRANCESA DE 300 MM', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'PISTOLA PARA TUBO DE FASTIX', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'CORTAFIERRO', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'DESTORNILLADOR PLANO 4X300 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'DESTORNILLADOR PLANO 6X300 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'DESTORNILLADOR PLANO 4X150 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'PIQUETA', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TIJERA DE SASTRE', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'DISCO DE COPA DE CERDAS DE BRONCE', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'CEPILLO MANUAL DE CERDAS DE ACERO', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'TUBO Nº29', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'GRASERA MANUAL', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'ESCUADRA', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'JUEGO DE LETRAS', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'AMOLADORA DE 180 MM', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'GRILLETE CORAZON 3/4"', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'GRILLETE CORAZON 1"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'GRILLETE CORAZON 1 1/4"', null, 8, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'GRILLETE CORAZON 2"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'GRILLETE CORAZON 2 1/2"', null, 3, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), 'Para chapa diamante de remolque'),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'GRILLETE U 1"', null, 3, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'GRILLETE U 1 1/2"', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), null),
  ('maquinas', 'HERRAMIENTAS MAQUINAS', 'GANCHO DE 5 TON', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de cubierta'), 'Uno sin traba de seguridad'),
  ('maquinas', 'MMPP MAK 8 M', 'CULATA COMPETA', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Sala de máquinas (SDM)'), null),
  ('maquinas', 'MMPP MAK 8 M', 'BOMBAS INYECTORAS', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Frente separador de sentinas'), null),
  ('maquinas', 'MMPP MAK 8 M', 'VALVULAS DE ARRANQUE', null, 3, (select id from atlantic_dama.ubicaciones where nombre = 'Frente separador de sentinas'), null),
  ('maquinas', 'MMPP MAK 8 M', 'INYECTORES', null, 4, (select id from atlantic_dama.ubicaciones where nombre = 'Frente separador de sentinas'), null),
  ('maquinas', 'MMPP MAK 8 M', 'VALVULAS', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Frente separador de sentinas'), null),
  ('maquinas', 'MMPP MAK 8 M', 'BARILLA DE BOTADOR', null, 4, (select id from atlantic_dama.ubicaciones where nombre = 'Frente separador de sentinas'), null),
  ('maquinas', 'MMPP MAK 8 M', 'CAÑO DE INYECCION', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Frente separador de sentinas'), null),
  ('maquinas', 'MMPP MAK 8 M', 'CAJA DE BALANCINES', null, 1, (select id from atlantic_dama.ubicaciones where nombre = ''), null),
  ('maquinas', 'MMAA SCANIA DI12', 'TACOS ANTIVIBRATORIOS', null, 6, (select id from atlantic_dama.ubicaciones where nombre = 'Taquilla BB (SDM)'), null),
  ('maquinas', 'MMAA SCANIA DI12', 'BOMBA DE ACEITE', null, 2, (select id from atlantic_dama.ubicaciones where nombre = ''), 'USADA. Ubicacion original (a revisar): Sobre taquilla de BB SDM y pañol timon'),
  ('maquinas', 'MMAA SCANIA DI12', 'BOMBA DE AGUA', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de timón'), 'USADAS'),
  ('maquinas', 'MMAA SCANIA DI12', 'BOMBIN DE COMBUSTIBLE', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'MMAA SCANIA DI12', 'ANTERNADOR 12 V', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'MMAA SCANIA DI12', 'CORREA 8PK1700', '6760-0001', 2, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), null),
  ('maquinas', 'MMAA SCANIA DI12', 'PISTON', null, 6, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de timón'), 'usados'),
  ('maquinas', 'MMAA SCANIA DI12', 'CAMISA', null, 6, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de timón'), 'usadas'),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'INYECTORES', 'X5228770', 16, (select id from atlantic_dama.ubicaciones where nombre = 'Taquilla BB (SDM)'), '12 recorridos 4 nuevos'),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'BOMBA DE COMBUSTIBLE GDES', null, 3, (select id from atlantic_dama.ubicaciones where nombre = 'Taquilla BB (SDM)'), '3 USADAS SEGÚN INVENTARIO'),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'BOMBA DE BARRIDO', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Frente a generador 2'), null),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'CULATA COMPLETA', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Frente a generador 2'), 'Condicion dudosa'),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'MANGUITO H318', 'H318', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'para eje de bow'),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'RODAMIENTO NTN 1218K', '12185K', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'para eje de bow'),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'JUEGO DE RETENES PARA CAJA DE ROD.', 'TSN 518L', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taller de máquinas'), 'Juego de 4 mitades. Para caja de bow'),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'RELE DE ARRANQUE BOW', 'RMR 9042', 2, (select id from atlantic_dama.ubicaciones where nombre = 'Camarote JDM'), null),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'IMPULSOR FW', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taquilla BB (SDM)'), 'Usada'),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'ROTOR DE GOMA', '6760-0001', 2, (select id from atlantic_dama.ubicaciones where nombre = 'Taquilla BB (SDM)'), 'Nuevos'),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'COJINETE DE CABEZA DE BIELA', 'CB-555 P', 8, (select id from atlantic_dama.ubicaciones where nombre = 'Taquilla BB (SDM)'), null),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'TAPA DE BANCADA', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taquilla BB (SDM)'), null),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'JUEGO DE AROS', '83939DC', 6, (select id from atlantic_dama.ubicaciones where nombre = 'Taquilla BB (SDM)'), '2 juegos con faltante de aro de fuego'),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'COJINETE DE BANCADA', '05439CC', 3, (select id from atlantic_dama.ubicaciones where nombre = 'Taquilla BB (SDM)'), null),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'ACOPLAMIENTO ASM', '5103377', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taquilla BB (SDM)'), null),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'RETEN DE ACEITE', 'B23507225', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taquilla BB (SDM)'), null),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'ELEMENTO DE INYECTOR BOMBA P&B N7', '5228682', 6, (select id from atlantic_dama.ubicaciones where nombre = 'Taquilla BB (SDM)'), null),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'TIP ASM DE INY', '5229192', 8, (select id from atlantic_dama.ubicaciones where nombre = 'Taquilla BB (SDM)'), null),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'TERMOSTATO 170ºC', '23503826', 4, (select id from atlantic_dama.ubicaciones where nombre = 'Taquilla BB (SDM)'), null),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'KIT BOMBA AGUA DE MAR', '011-05194860', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taquilla BB (SDM)'), null),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'EJE BOMBA ACOPLADA DE MAR', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Taquilla BB (SDM)'), 'PARA BOW THRUSTER'),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'SELLO BOMBA AGUA DE MAR', '1 2954945', 2, (select id from atlantic_dama.ubicaciones where nombre = 'Taquilla BB (SDM)'), 'GR 56170'),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'RODAMIENTO', '1 2954945', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taquilla BB (SDM)'), null),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'RETEN SK-293', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Taquilla BB (SDM)'), null),
  ('maquinas', 'MMAA EGA Y BOW GM SERIE 71', 'PORTA INYECTOR', null, 9, (select id from atlantic_dama.ubicaciones where nombre = 'Taquilla BB (SDM)'), null),
  ('maquinas', 'COMPRESORES DE AIRE QUINCY', 'CONJUNTO VALVULA DE DESCARGA', '7271X 002', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de proa'), 'USADA'),
  ('maquinas', 'COMPRESORES DE AIRE QUINCY', 'JUNTAS', '1852', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de proa'), null),
  ('maquinas', 'COMPRESORES DE AIRE QUINCY', 'BIELA COMPLETA', '110802', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de proa'), 'CON ROD TORRINGTON'),
  ('maquinas', 'COMPRESORES DE AIRE QUINCY', 'JUNTA DE TAPA DE INSPECCIÒN', '1315', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de proa'), null),
  ('maquinas', 'COMPRESORES DE AIRE QUINCY', 'JUNTA DE VALVULA', '1848', 5, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de proa'), null),
  ('maquinas', 'COMPRESORES DE AIRE QUINCY', 'RODAMIENTO DE PIE DE BIELA TORRINGTON', 'T0618P42641g', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de proa'), null),
  ('maquinas', 'COMPRESORES DE AIRE QUINCY', 'COJINETE DE BIELA DE ALTA Y BAJA', '6443SR', 3, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de proa'), null),
  ('maquinas', 'COMPRESORES DE AIRE QUINCY', 'KIT BOMBA DE ACEITE', '160079', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de proa'), null),
  ('maquinas', 'COMPRESORES DE AIRE QUINCY', 'KIT DE RODAMIENTOS', '110799-101', 2, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de proa'), null),
  ('maquinas', 'COMPRESORES DE AIRE QUINCY', 'ESPIGAS ROLL PIN', '110705-F17', 2, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de proa'), null),
  ('maquinas', 'COMPRESORES DE AIRE QUINCY', 'CASQUILLO DE BIELAS', '6656 PR', 2, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de proa'), 'USADOS'),
  ('maquinas', 'COMPRESORES DE AIRE QUINCY', 'TAPON DE CIGÜEÑAL', '121160', 2, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de proa'), null),
  ('maquinas', 'COMPRESORES DE AIRE QUINCY', 'JUNTA DE GOMA PARA DESCARGADOR', '1855', 4, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de proa'), null),
  ('maquinas', 'COMPRESORES DE AIRE QUINCY', 'DESCARGADORES', '8572X', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de proa'), null),
  ('maquinas', 'COMPRESORES DE AIRE QUINCY', 'DESCARGADORES', '7483X', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de proa'), null),
  ('maquinas', 'COMPRESORES DE AIRE QUINCY', 'JUEGO DE JUNTAS', '7088', 2, (select id from atlantic_dama.ubicaciones where nombre = 'Pañol de proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'KIT HUMEDO BOMBA 1in', '8050062511', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'DISCO ACOPLE T.REX', '0013-00162479', 27, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), 'CONDICION DUDOSA'),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'PROTECTION TUBE', '1.1740-001', 2, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'CLAMPING CONE HALF', '1.2210-007', 64, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'PISTON RING STARTING VALVE', '1.2240-014', 48, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'PISTON RING STARTING VALVE', '1.2240-015', 2, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'SAFETY VALVE', '1.2250-005', 2, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'MALE CONNECTOR', '1.2250-102', 4, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'CONNECTING NUT', '1.2250-103', 4, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'PROTECTION TUBE', '1.2260-002', 4, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'NOZZLE ELEMENT', '1.2260-003', 4, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'NOZZLE SPRING', '1.2267-058', 20, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'ROLLER WITH BUSH', '1.3565-011', 4, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'VARILLA DE BOTADOR', '1.3570A', 4, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'PUMP ELEMENT', '1.3597-005', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'CONTROL RACK', '1.3597-019', 2, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'CONTROL PISTON', '1.4450-002', 16, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'SPRING', '1.4450-004', 16, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'BUSH F. START. AIR DISTRIBUTOR', '1.4450-007', 16, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'VALVULA REGULADORA DE PRESION 1.5-6BAR', '1.4904AA', 2, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'KIT REPARACION', '1.4906-901', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'JOINT RING', '1.7010-154', 8, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'JOINT RING', '1.7010-196', 16, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'RUBBER SLEEVE', '1.7230-004', 2, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'HOSE CLAMP', '1.7230-006', 13, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'PRESS SPRING', '1.7810-004', 2, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'RODAMIENTO NTN', '12185k', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'JUNTAS DE CAMISA MOTOR PPAL', '273384-1', 15, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'ST,RING,PISTON,STANDARD SIZE', '7595A', 4, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), 'INB1983439'),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'CLAMP SLEEVE FAG', 'H132.150.D', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), 'BALLB001115'),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'MS-17 ROUND RUBBER RING AFT SEAL', 'SIMP000033', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'MS-8 GASKET', 'SIMP000288', 2, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'MS-9 SEALING RING', 'SIMP000289', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'MS-80 FLANGE PACHING-C', 'SIMP000291', 2, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'MS-99 SMALL PARTS SSA', 'SIMP000293', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'MS-16 RUBBER RING 30mm', 'SIMP000327', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'MS-81 FLANGE PACKING-B', 'SIMP000573', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'MS-8 SEALING RING', 'SIMP000924', 2, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'MS-99 SMALL PARTS SSA FWD', 'SIMP000926', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'ROLLER', 'T3565-011', 7, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'GUIAS DE VALVULA', null, 64, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'CAÑOS DE INYECCION', null, 2, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'COJINETES DE BIELA EQUIVOCADOS', null, 3, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), 'EQUIVOCADOS'),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'STAY DE CULATA', null, 12, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), 'CORROÍDOS'),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'ACOPLE FLEXIBLE VULCAN', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'VALVULA MARIPOSA WAFER', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), null),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'SELLOS LINEA DE EJE VARIOS', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), 'A REVISAR'),
  ('maquinas', 'LISTADO INVENTARIO DE PROA', 'REPUESTOS QUINCY VARIOS', null, 1, (select id from atlantic_dama.ubicaciones where nombre = 'Proa'), 'A REVISAR')
) as t (categoria, grupo, nombre, codigo, cantidad, ubicacion_id, comentarios);
-- Datos migrados desde "AD - Towing gear summary.xlsx" (hojas Towing y Quarantine Items).
insert into atlantic_dama.ubicaciones (nombre) values
  ('Bodega'),
  ('Lower drum'),
  ('Main Tow Wire'),
  ('Spare Tow Wire'),
  ('Upper drum');

insert into atlantic_dama.inventario_items
  (categoria, nombre, codigo, cantidad, ubicacion_id, marca, wll_mbl, fecha_referencia, estado, comentarios)
select * from (values
  ('towing_gear', 'Main Tow Wire', '262386', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Lower drum'), 'Haggie', 'MBL 350T', date '2019-06-11', 'activo', '1219m x 71mm with closed spelter socket'),
  ('towing_gear', 'Spelter Socket', '20190326-01', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Main Tow Wire'), 'De Haan', 'MBL 500T', date '2019-05-02', 'activo', 'Closed'),
  ('towing_gear', 'Spare Tow Wire', '520220', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Upper drum'), 'IPH', 'MBL 193T', date '2025-08-12', 'activo', '750m x 52mm with closed spelter socket'),
  ('towing_gear', 'Spelter Socket', 'CC1-2025081200191', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Spare Tow Wire'), 'Crosby', 'MBL 309T', date '2025-08-12', 'activo', 'Closed'),
  ('towing_gear', 'Spare Wire', 'EXS/19/19988-2', 1, (select id from atlantic_dama.ubicaciones where nombre = ''), 'Exsil NV', 'MBL 55T', date '2019-12-19', 'activo', '1500m x 28mm. Astillero'),
  ('towing_gear', 'Spare Wire', 'EXS/19/19988-1', 1, (select id from atlantic_dama.ubicaciones where nombre = ''), 'Exsil NV', 'MBL 55T', date '2019-12-19', 'activo', '500m x 28mm. Astillero'),
  ('towing_gear', 'Spelter Socket', 'EXS/19/19988-3', 1, (select id from atlantic_dama.ubicaciones where nombre = ''), 'Exsil NV', 'MBL 80T', date '2019-12-19', 'activo', 'Closed. Astillero'),
  ('towing_gear', 'Spelter Socket', 'EXS/19/19988-4', 1, (select id from atlantic_dama.ubicaciones where nombre = ''), 'Exsil NV', 'MBL 8T', date '2019-12-19', 'activo', 'Open. Astillero'),
  ('towing_gear', 'Poliprop Rope', '10227CHN20', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'Jiuli Rope Co Ltd', 'MBL 90T', date '2020-06-20', 'activo', '70m x 90mm'),
  ('towing_gear', 'Shackle', '82304223/110', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'Gunnebo', 'WLL 35T', date '2019-01-31', 'activo', 'Bolt Type'),
  ('towing_gear', 'Shackle', '82304223/110', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'Gunnebo', 'WLL 35T', date '2019-01-31', 'activo', 'Bolt Type'),
  ('towing_gear', 'Shackle', '82304223/110', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'Gunnebo', 'WLL 35T', date '2019-01-31', 'activo', 'Bolt Type'),
  ('towing_gear', 'Shackle', '20H013557', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'Crosby', 'WLL 55T', date '2020-01-30', 'activo', 'Bolt Type - #9643.05'),
  ('towing_gear', 'Shackle', '20H013557', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'Crosby', 'WLL 55T', date '2020-01-30', 'activo', 'Bolt Type - #9643.06'),
  ('towing_gear', 'Shackle', '20H013557', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'Crosby', 'WLL 55T', date '2020-01-30', 'activo', 'Bolt Type - #9643.07'),
  ('towing_gear', 'Shackle', 'CE-C-1216-14-162-04-9A', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'JULI Sling Co', 'WLL 25T', date '2014-12-31', 'activo', 'Bow type (Bolt & Nut). Tuerca y chaveta azul'),
  ('towing_gear', 'Shackle', 'CE-C-1216-14-162-04-9A', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'JULI Sling Co', 'WLL 25T', date '2014-12-31', 'activo', 'Bow type (Bolt & Nut). Tuerca y chaveta azul'),
  ('towing_gear', 'Shackle', 'CE-C-1216-14-162-04-9A', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'JULI Sling Co', 'WLL 25T', date '2014-12-31', 'activo', 'Bow type (Bolt & Nut). Tuerca y chaveta azul'),
  ('towing_gear', 'Shacke', 'CE-C-1216-14-162-04-9A', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'JULI Sling Co', 'WLL 25T', date '2014-12-31', 'activo', 'Bow type (Bolt & Nut). Tuerca y chaveta azul'),
  ('towing_gear', 'Shackle', '2104-8307', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'ELD', 'WLL 17T', date '2021-04-22', 'activo', 'Bow type'),
  ('towing_gear', 'Shackle', '2104-8307', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'ELD', 'WLL 17T', date '2021-04-22', 'activo', 'Bow type'),
  ('towing_gear', 'Shackle', '2104-8307', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'ELD', 'WLL 17T', date '2021-04-22', 'activo', 'Bow type'),
  ('towing_gear', 'Shackle', '133844', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'ELD', 'WLL 12T', date '2021-04-22', 'activo', 'Bow type'),
  ('towing_gear', 'Shackle', '133844', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'ELD', 'WLL 12T', date '2021-04-22', 'activo', 'Bow type'),
  ('towing_gear', 'Shackle', '133844', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'ELD', 'WLL 12T', date '2021-04-22', 'activo', 'Bow type'),
  ('towing_gear', 'Shackle', '133844', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'ELD', 'WLL 12T', date '2021-04-22', 'activo', 'Bow type'),
  ('towing_gear', 'Shackle', '133844', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'ELD', 'WLL 12T', date '2021-04-22', 'activo', 'Bow type'),
  ('towing_gear', 'Delta Plate', '20H013581', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'Lankhorst', 'WLL 35T', date '2020-02-13', 'activo', 'Triangle - #105363'),
  ('towing_gear', 'Delta Plate', '20H013581', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'Lankhorst', 'WLL 55T', date '2020-02-13', 'activo', 'Triangle - #923131'),
  ('towing_gear', 'Pennant Wire', '3018/20', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'Steelropes', 'MBL 137T', date '2020-09-16', 'activo', '36m x 44mm'),
  ('towing_gear', 'Pennant Wire', '445892', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'IPH', 'MBL 138T', date '2021-11-04', 'activo', '18m x 44mm'),
  ('towing_gear', 'Pennant Wire', '445892', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'IPH', 'MBL 138T', date '2021-11-04', 'activo', '18m x 44mm'),
  ('towing_gear', 'Chain', 'JJG2010496/1', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'Jiangsu', 'MBL 15T', date '2020-08-18', 'activo', '27.5m x 16mm'),
  ('towing_gear', 'Poliprop Rope', 'JM-04520-N2', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'Moscuzza', 'MBL 47T', date '2023-08-01', 'activo', 'TYPE POLYSTEEL 56mm x 220m'),
  ('towing_gear', 'Poliprop Rope', 'JM-04521-N2', 1, (select id from atlantic_dama.ubicaciones where nombre = 'Bodega'), 'Moscuzza', 'MBL 47T', date '2023-08-01', 'activo', 'TYPE POLYSTEEL 56mm x 220m')
) as t (categoria, nombre, codigo, cantidad, ubicacion_id, marca, wll_mbl, fecha_referencia, estado, comentarios);
